name: Deploy to Maven Repository

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 8
          cache: maven
          server-id: openmrs-repo-modules
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Deploy to OpenMRS Maven Repository
        run: mvn clean deploy -B -DskipTests
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
